version: "3.8"
services:
  #serviço de estoque
  stock-service: 
    build: 
      context: ./StockService
      dockerfile: Dockerfile
    container_name: stock-service
    ports:
      ["8080:8080"]
    environment:
      ConnectionStrings__SqlServer: "Server=db-sqlserver;Database=StockServiceDB;User Id=SA;Password=${STOCK_SERVICE_DB_PASSWORD};Encrypt=True;TrustServerCertificate=True;"
    depends_on:
      - db-sqlserver
  
  #banco de dados do serviço de estoque
  db-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: StockServiceDB
    ports:
     ["1433:1433"]
    environment:
      ACCEPT_EULA: "Y"
      SMSSQL_SA_PASSWORD: ${STOCK_SERVICE_DB_PASSWORD}
    volumes:
      - sqlserver-data:/var/opt/mssql
    restart: always

volumes:
  sqlserver-data:
